# Transmission - Torrent Client
# BitTorrent download client

name: transmission
description: Torrent download client
category: media
subdomain: transmission

access:
  groups: [admins]
  public: false

dependencies:
  - traefik
  - tailscale-access
