# Plex - Media Server
# Commercial media streaming server

name: plex
description: Plex media server
category: media
subdomain: plex

access:
  groups: [admins]
  public: false

dependencies:
  - traefik
  - tailscale-access
