services:
  donetick:
    image: donetick/donetick:v0.1.74
    container_name: donetick
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    security_opt:
      - no-new-privileges:true
    networks:
      - nexus
    volumes:
      - ${NEXUS_DATA_DIRECTORY}/Config/donetick/data:/donetick-data
      - ${NEXUS_ROOT_DIRECTORY}/services/donetick/config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
      - DT_JWT_SECRET=${DONETICK_JWT_SECRET}
      - DT_JWT_SESSION_TIME=168h
      - DT_JWT_MAX_REFRESH=1440h
      - DT_STORAGE_ENDPOINT=${DONETICK_R2_ENDPOINT}
      - DT_STORAGE_BUCKET_NAME=${DONETICK_R2_BUCKET}
      - DT_STORAGE_ACCESS_KEY=${DONETICK_R2_ACCESS_KEY}
      - DT_STORAGE_SECRET_KEY=${DONETICK_R2_SECRET_KEY}
      - DT_STORAGE_REGION=us-east-1
      - DT_STORAGE_BASE_PATH=uploads
      - DT_STORAGE_MAX_USER_STORAGE=104857600 # 100mb
      - DT_STORAGE_MAX_FILE_SIZE=10485760 # 10mb
      - TZ=${TZ}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:2021",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nexus"
      - "traefik.http.services.donetick.loadbalancer.server.port=2021"
      - "traefik.http.routers.donetick.rule=Host(`donetick.${NEXUS_DOMAIN}`)"
      - "traefik.http.routers.donetick.entrypoints=https"
      - "traefik.http.routers.donetick.middlewares=tailscale-chain@file"
      - "traefik.http.routers.donetick.tls=true"
      - "traefik.http.routers.donetick.tls.certresolver=certchallenge"

networks:
  nexus:
    external: true
